
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.0
 * Query Engine version: ab56fe763f921d033a6c195e7ddeb3e255bdbb57
 */
Prisma.prismaVersion = {
  client: "7.4.0",
  engine: "ab56fe763f921d033a6c195e7ddeb3e255bdbb57"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  clerkId: 'clerkId',
  email: 'email',
  collegeName: 'collegeName',
  name: 'name',
  profileAvatar: 'profileAvatar',
  password: 'password',
  createdAt: 'createdAt',
  vToken: 'vToken',
  expiryToken: 'expiryToken',
  ValidFor: 'ValidFor',
  isVerified: 'isVerified',
  clubName: 'clubName',
  clubId: 'clubId',
  bio: 'bio',
  tags: 'tags',
  course: 'course',
  year: 'year',
  phone: 'phone',
  twitter: 'twitter',
  linkedin: 'linkedin',
  instagram: 'instagram'
};

exports.Prisma.ClubsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  founderEmail: 'founderEmail',
  coremember1: 'coremember1',
  coremember2: 'coremember2',
  coremember3: 'coremember3',
  facultyEmail: 'facultyEmail',
  collegeName: 'collegeName',
  collegeId: 'collegeId',
  type: 'type',
  description: 'description',
  requirements: 'requirements',
  profilePicUrl: 'profilePicUrl',
  clubContact: 'clubContact',
  wings: 'wings',
  instagram: 'instagram',
  twitter: 'twitter',
  linkedin: 'linkedin'
};

exports.Prisma.CreatePostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  published: 'published',
  collegeName: 'collegeName',
  clubName: 'clubName',
  collegeId: 'collegeId',
  authorId: 'authorId'
};

exports.Prisma.SpeakersScalarFieldEnum = {
  id: 'id',
  profilePic: 'profilePic',
  about: 'about',
  name: 'name',
  email: 'email',
  eventId: 'eventId'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  posterUrl: 'posterUrl',
  EventMode: 'EventMode',
  EventType: 'EventType',
  eventHeaderImage: 'eventHeaderImage',
  EventName: 'EventName',
  description: 'description',
  tagline: 'tagline',
  prizes: 'prizes',
  TeamSize: 'TeamSize',
  Venue: 'Venue',
  EventUrl: 'EventUrl',
  applicationStatus: 'applicationStatus',
  applicationStartDate: 'applicationStartDate',
  applicationEndDate: 'applicationEndDate',
  clubName: 'clubName',
  clubId: 'clubId',
  university: 'university',
  createdAt: 'createdAt',
  startDate: 'startDate',
  endDate: 'endDate',
  collegeStudentsOnly: 'collegeStudentsOnly',
  participationFee: 'participationFee',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  Form: 'Form',
  Fees: 'Fees',
  link1: 'link1',
  link2: 'link2',
  link3: 'link3',
  whatsappLink: 'whatsappLink',
  isPaid: 'isPaid',
  qrCodeUrl: 'qrCodeUrl'
};

exports.Prisma.EventAnnouncementScalarFieldEnum = {
  id: 'id',
  Title: 'Title',
  Description: 'Description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  eventId: 'eventId'
};

exports.Prisma.EventGalleryScalarFieldEnum = {
  id: 'id',
  imageUrl: 'imageUrl',
  caption: 'caption',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  eventId: 'eventId'
};

exports.Prisma.ClubAnnouncementScalarFieldEnum = {
  id: 'id',
  Title: 'Title',
  Description: 'Description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  clubId: 'clubId'
};

exports.Prisma.UserEventsScalarFieldEnum = {
  userId: 'userId',
  eventId: 'eventId',
  uniquePassId: 'uniquePassId',
  joinedAt: 'joinedAt',
  paymentScreenshotUrl: 'paymentScreenshotUrl',
  paymentStatus: 'paymentStatus',
  paymentVerifiedAt: 'paymentVerifiedAt'
};

exports.Prisma.PostUpvoteScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.PostDownvoteScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  clubs: 'clubs',
  CreatePost: 'CreatePost',
  speakers: 'speakers',
  event: 'event',
  eventAnnouncement: 'eventAnnouncement',
  eventGallery: 'eventGallery',
  clubAnnouncement: 'clubAnnouncement',
  userEvents: 'userEvents',
  PostUpvote: 'PostUpvote',
  PostDownvote: 'PostDownvote'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
